// Builds db/seeds/recipe-library.sql from the DIY Dog dataset (github.com/alxiw/punkapi, MIT).
//
//   git clone https://github.com/alxiw/punkapi /tmp/punkapi
//   npm run library:build -- /tmp/punkapi
//
// Every recipe is converted with the same adapter the app uses and validated against the recipe
// schema; the build fails on the first invalid recipe rather than seeding bad data.
import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { convertDiyDogBeer, diyDogSearchText, type DiyDogBeer } from "../src/domain/import/diy-dog.ts";
import { libraryCategoryLabels } from "../src/domain/model/library.ts";
import { recipeDocumentSchema } from "../src/domain/model/recipe.ts";

const repo = process.argv[2];
if (!repo) {
  console.error("Usage: npm run library:build -- <path to punkapi clone>");
  process.exit(1);
}
const commit = execFileSync("git", ["-C", repo, "rev-parse", "HEAD"], { encoding: "utf8" }).trim();
const dataDir = join(repo, "data");
const files = readdirSync(dataDir).filter((f) => f.endsWith(".json")).sort();

const sqlString = (value: string | null | undefined) => (value == null ? "NULL" : `'${value.replaceAll("'", "''")}'`);
const sqlNumber = (value: number | null | undefined) => (typeof value === "number" && Number.isFinite(value) ? String(value) : "NULL");

const importedAt = Date.now();
const lines = [
  "-- Generated by scripts/build-recipe-library.ts — do not edit by hand.",
  `-- Source: https://github.com/alxiw/punkapi @ ${commit} (MIT). ${files.length} recipes.`,
];
let warningCount = 0;
const invalid: string[] = [];
const categories: Record<string, number> = {};

for (const file of files) {
  const raw = readFileSync(join(dataDir, file), "utf8");
  const beer = JSON.parse(raw) as DiyDogBeer;
  const { recipe, category, warnings } = convertDiyDogBeer(beer);
  const parsed = recipeDocumentSchema.safeParse(recipe);
  if (!parsed.success) {
    invalid.push(`${file} (${beer.name}): ${parsed.error.issues.map((i) => `${i.path.join(".")} ${i.message}`).join("; ")}`);
    continue;
  }
  const ref = file.replace(/\.json$/, "");
  warningCount += warnings.length;
  categories[category] = (categories[category] ?? 0) + 1;
  const values = [
    sqlString(`diydog-${ref}`),
    sqlString("diydog"),
    sqlString(ref),
    sqlString(`https://github.com/alxiw/punkapi/blob/${commit}/data/${file}`),
    sqlString(recipe.name),
    sqlString(beer.tagline ?? null),
    sqlString(category),
    sqlNumber(recipe.targets.abvPct),
    sqlNumber(recipe.targets.ibu),
    sqlNumber(recipe.targets.og),
    sqlNumber(recipe.targets.fg),
    sqlNumber(recipe.targets.colorEbc),
    sqlNumber(recipe.batchSizeL),
    sqlString(diyDogSearchText(beer, libraryCategoryLabels[category])),
    sqlString(JSON.stringify(parsed.data)),
    sqlString(JSON.stringify(beer)),
    sqlString(JSON.stringify(warnings)),
    String(importedAt),
  ];
  lines.push(
    `INSERT OR REPLACE INTO recipe_library (id, source, source_ref, source_url, name, tagline, category, abv, ibu, og, fg, ebc, batch_size_l, search_text, data, source_data, warnings, imported_at) VALUES (${values.join(", ")});`,
  );
}

if (invalid.length > 0) {
  console.error(`${invalid.length} recipes failed validation:\n${invalid.join("\n")}`);
  process.exit(1);
}

writeFileSync("db/seeds/recipe-library.sql", `${lines.join("\n")}\n`);
console.log(`Wrote ${files.length} recipes to db/seeds/recipe-library.sql (${warningCount} interpretation notes).`);
console.log("Categories:", categories);
