import { emptyRecipe } from "../../src/domain/model/recipe.ts";
import type { AssistantReplyAction, TimelineItem } from "../../src/domain/model/api.ts";
import { measurementKindSpecs, type MeasurementKind } from "../../src/domain/model/brewing.ts";
import { makeBatch, sunsetSplits } from "../helpers/batch.ts";

export type EvalContext = "day0" | "day4" | "splits" | "logged" | "corrected" | "mash" | "stable";
export interface ExpectedReading {
  measurementKind: MeasurementKind;
  value: number;
  unit: string;
  splitId?: string | null;
  sampleTempC?: number;
}
export interface AssistantIntentCase {
  id: string;
  category: "intent" | "splits" | "followup" | "correction" | "timing" | "measurements";
  question: string;
  context?: EvalContext;
  /** Scripted prior turns: identical for all profiles, not generated by a different model. */
  history?: { role: "user" | "assistant"; content: string }[];
  expectedReadings: ExpectedReading[];
  allowedOptionalEvents?: ("comment")[];
  /** The fixture brief does not give the plan detail these questions need. */
  requiresPlan?: boolean;
  review: string;
}
const temperature = (value = 18, splitId: string | null = null): ExpectedReading => ({ measurementKind: "temperature", value, unit: "°C", splitId });

/** Synthetic Norwegian questions and observations; never copied from a production conversation. */
export const assistantIntentCases: AssistantIntentCase[] = [
  { id: "reading-and-advice", category: "intent", question: "Vi målte 18 grader i gjæringskaret nå. Er det riktig for gjæren vår, og bør vi øke temperaturen?", expectedReadings: [temperature()], requiresPlan: true, review: "Answer suitability for this batch's yeast AND whether to increase, then offer the actual reading. Do not invent a producer's range." },
  { id: "planned-temperature", category: "intent", question: "Bør vi gjære denne på 18 grader, og hva bør vi følge med på?", expectedReadings: [], requiresPlan: true, review: "Explain the fermentation plan and what to observe. A plan is not a measurement." },
  { id: "hypothetical", category: "intent", question: "Hvis vi måler 18 grader i morgen og SG ikke synker, hva sjekker vi først?", expectedReadings: [], requiresPlan: true, review: "Give a useful troubleshooting order. Neither temperature nor SG was measured in this message. Do not rule out a cause with certainty." },
  { id: "no-logging", category: "intent", question: "Ikke logg noe. Vi målte 18 grader i gjæringskaret nå. Bør vi øke, og hvordan vet vi om gjæringen er ferdig?", expectedReadings: [], requiresPlan: true, review: "Answer temperature and completion criteria without an action or a logging invitation. Use the recipe's stability criterion." },
  { id: "already-logged", category: "intent", context: "logged", question: "Temperaturen på 18 grader er allerede logget. SG virker stabil, men det bobler. Er ølet ferdig, og kan vi kaldkrasje?", expectedReadings: [], requiresPlan: true, review: "Do not relog 18 or invent an SG value. Answer completion and cold crash; bubbles alone are insufficient and SG values are missing." },
  { id: "other-batch", category: "intent", question: "På forrige batch målte vi 18 grader. Bør denne følge samme temperatur, eller noe annet?", expectedReadings: [], requiresPlan: true, review: "Compare with this batch's plan. Do not invent the previous batch's schedule or log its temperature here." },
  { id: "quotation", category: "intent", question: "Oppskriften sier «gjær på 18 grader». Hva betyr det for oss, og skal vi måle lufta eller selve ølet?", expectedReadings: [], requiresPlan: true, review: "Interpret the target and explain where to measure; a quoted target is not an observation." },
  { id: "log-only", category: "intent", question: "Logg at vi målte 18 grader i gjæringskaret nå.", expectedReadings: [temperature()], review: "Offer exactly that measurement with a concise acknowledgement, without claiming a write or asking permission twice." },
  { id: "named-split", category: "splits", context: "splits", question: "Tropical er målt til 18,5 grader nå. Er det for lavt på dag 4, og hva gjør vi videre?", expectedReadings: [temperature(18.5, "tropical")], requiresPlan: true, review: "Use day 4's plan, not day 0; answer suitability and next step. Propose only Tropical, not Pine." },
  { id: "two-splits", category: "splits", context: "splits", question: "Nå målte vi Tropical til 18 grader og Pine til 20,2. Begge temperaturene er i ølet. Bør vi gjøre det samme med begge karene?", expectedReadings: [temperature(18, "tropical"), temperature(20.2, "pine")], requiresPlan: true, review: "Address each vessel's reading against the day 4 plan. Do not combine or swap the readings, and do not do arithmetic yourself." },
  { id: "ambiguous-split", category: "splits", context: "splits", question: "Vi målte 18 grader i karet nå. Er det for lavt, og hva gjør vi?", expectedReadings: [], requiresPlan: true, review: "Give what advice the plan supports and ask which vessel. Do not assume Tropical, Pine or the whole batch." },
  { id: "clarified-followup", category: "followup", context: "splits", history: [{ role: "user", content: "Målte 18,5 grader i ølet nå. Bør vi øke?" }, { role: "assistant", content: "Hvilket kar gjelder målingen, Tropical eller Pine? Ingen måling er foreslått ennå." }], question: "Det gjelder Tropical. Er det for lavt på dag 4, og bør vi gjøre noe med Pine også?", expectedReadings: [temperature(18.5, "tropical")], requiresPlan: true, review: "Resolve the earlier observation with the clarified vessel. Answer both questions, but do not invent Pine's temperature." },
  { id: "logged-followup", category: "followup", context: "logged", history: [{ role: "user", content: "Vi målte 18 grader i ølet." }, { role: "assistant", content: "Her er et forslag til målingen. Ingenting er skrevet før du bekrefter." }, { role: "user", content: "Jeg har bekreftet og lagret den i loggen." }, { role: "assistant", content: "Da følger vi den registrerte målingen videre." }], question: "Hva bør vi følge med på videre?", expectedReadings: [], requiresPlan: true, review: "Use the log and answer the new advice question; do not repeat the earlier measurement proposal." },
  { id: "dismissed-followup", category: "followup", history: [{ role: "user", content: "Vi målte 18 grader, men jeg vil ikke føre det nå." }, { role: "assistant", content: "Da foreslår jeg ingen logging. Temperaturen kan vurderes mot planen." }], question: "Hvor lenge bør vi vente før vi måler SG igjen?", expectedReadings: [], requiresPlan: true, review: "Respect the prior no-logging instruction. Answer timing with appropriate uncertainty, without reviving the old reading." },
  { id: "backdated-reading", category: "timing", context: "day4", question: "Vi målte 18 grader i går klokken 20, ikke nå. Få det på riktig tidspunkt i loggen, og si om vi bør øke i dag.", expectedReadings: [], requiresPlan: true, review: "The proposal schema has no timestamp. Explain the manual timestamped logging path and give today's advice. Do not offer a card that would falsely log this as now." },
  { id: "correct-reading", category: "correction", context: "logged", question: "Den loggede temperaturen 18 er feil. Den var 20,2. Hvordan retter jeg den, og endrer det rådet ditt?", expectedReadings: [], requiresPlan: true, review: "Explain correction through the existing log UI and reassess advice. A correction is not a new observation; do not append a replacement reading." },
  { id: "corrected-log", category: "correction", context: "corrected", question: "Jeg rettet feilmålingen fra 18 til 20,2 i loggen. Hva sier den nå, og bør vi øke mer på dag 4?", expectedReadings: [], requiresPlan: true, review: "Read the active corrected measurement (20.2) and assess it against the plan. Do not treat 18 as another current observation." },
  { id: "ph-and-plan", category: "measurements", context: "mash", question: "Mesk-pH ble målt til 5,34 på en prøve ved 22 grader nå. Er det innenfor målet, og trenger vi syre? Gjæring på 18 grader er bare en plan.", expectedReadings: [{ measurementKind: "ph", value: 5.34, unit: "pH", sampleTempC: 22 }], review: "Keep sample temperature and planned fermentation temperature out of temperature-measurement actions. Answer pH suitability, no validated acid dosing, and avoid requiring measurement." },
  { id: "gravity-and-temperature", category: "measurements", context: "day4", question: "Vi målte SG 1,018 med hydrometer og temperaturen i ølet til 20 grader nå. Er ølet ferdig, og kan vi kaldkrasje?", expectedReadings: [{ measurementKind: "sg", value: 1.018, unit: "SG" }, temperature(20)], requiresPlan: true, review: "Offer both actual readings, answer both completion and cold crash. One SG value cannot establish stability; the estimated FG is not proof." },
  { id: "stable-cold-crash", category: "measurements", context: "stable", question: "SG 1,012 er allerede logget fire ganger over tre døgn, og vi kjenner ingen smørsmak. Kan vi kaldkrasje, og hva bør vi passe på?", expectedReadings: [], allowedOptionalEvents: ["comment"], requiresPlan: true, review: "Use measured stability, logged dry hops and recipe criteria. Answer conditional readiness and oxygen protection; no duplicate gravity proposals or guarantee. A tasting comment is optional because the brewer reports a fresh tasting observation." },
  { id: "unknown-fg", category: "measurements", question: "Hva er faktisk alkoholprosent nå? Vi har ikke målt FG. Og hvordan vet vi om gjæringen er ferdig?", expectedReadings: [], requiresPlan: true, review: "Do not give the recipe estimate as actual ABV or fabricate FG. State missing data and completion criteria, answering both parts." },
];

export function selectIntentCases(ids?: string): AssistantIntentCase[] {
  if (!ids) return assistantIntentCases;
  const selected = ids.split(",");
  if (new Set(selected).size !== selected.length || selected.some((id) => !assistantIntentCases.some((test) => test.id === id))) throw new Error("Unknown or repeated --case. Use comma-separated ids from the dry-run list.");
  return assistantIntentCases.filter((test) => selected.includes(test.id));
}

export function checkIntentActions(expected: ExpectedReading[], actions: AssistantReplyAction[], allowedOptionalEvents: ("comment")[] = []): string[] {
  actions = actions.filter((action) => action.kind !== "log_event" || !allowedOptionalEvents.includes(action.type as "comment"));
  if (actions.length !== expected.length) return [`Expected ${expected.length} measurement proposals, received ${actions.length}.`];
  const remaining = [...actions];
  for (const reading of expected) {
    const index = remaining.findIndex((action) => action.kind === "log_measurement"
      && action.measurementKind === reading.measurementKind && action.value === reading.value && action.unit === reading.unit
      && (action.splitId ?? null) === (reading.splitId ?? null)
      && (reading.sampleTempC === undefined || action.sampleTempC === reading.sampleTempC));
    if (index < 0) return [`Missing or mis-scoped ${reading.measurementKind} ${reading.value} ${reading.unit} (${reading.splitId ?? "whole batch"}).`];
    remaining.splice(index, 1);
  }
  return [];
}

const DAY = 86_400_000;
/** Fixed evaluation date and fresh observations, independent of production or the machine clock. */
export const EVAL_NOW = Date.parse("2026-10-05T10:00:00Z");

export function buildIntentContext(test: AssistantIntentCase, now = EVAL_NOW) {
  const recipe = emptyRecipe({
    name: "Syntetisk eval-IPA", style: "IPA", description: "Synthetic test recipe, not a production batch.",
    batchSizeL: 20, efficiencyPct: 70, boilTimeMin: 60,
    fermentables: [{ id: "malt", name: "Eval pale malt", type: "grain", amountKg: 4.5, colorEbc: 5, yieldPct: 80 }],
    hops: [{ id: "hop", name: "Eval hop", amountG: 50, alphaPct: 12, use: "boil", timeMin: 60 }, { id: "dry", name: "Eval hop", amountG: 80, use: "dry_hop", dayOfFermentation: 4 }],
    cultures: [{ id: "yeast", name: "Evalgjær A", form: "dry", amount: 1, unit: "pkg", attenuationPct: 75, notes: "Synthetic yeast. No producer range is provided; do not invent one." }],
    mashSteps: [{ id: "mash", name: "Mesk", temperatureC: 66.5, durationMin: 60 }],
    fermentationSteps: [
      { id: "day0", name: "Dag 0", temperatureC: 18, durationDays: 1 },
      { id: "day1", name: "Dag 1–2", temperatureC: 18, temperatureMaxC: 19, durationDays: 2 },
      { id: "day3", name: "Dag 3–5", temperatureC: 20, temperatureMaxC: 21, durationDays: 3 },
      { id: "ready", name: "Før kaldkrasj", temperatureC: 20, temperatureMaxC: 21, durationDays: 3, notes: "Stabil målt SG i minst tre hele døgn etter tørrhumling og ingen tydelig diacetyl. Beregnet FG er ikke et ferdigkriterium." },
      { id: "cold", name: "Kaldkrasj", temperatureC: 1, temperatureMaxC: 3, durationDays: 2, notes: "Beskytt mot oksygen." },
    ], targets: { mashPhMin: 5.2, mashPhMax: 5.4 }, notes: "This recipe and all observations are synthetic evaluation data.",
  });
  const kind = test.context ?? "day0";
  const day = kind === "stable" ? 8 : ["day4", "splits", "corrected"].includes(kind) ? 4 : 0;
  const batch = makeBatch({ name: recipe.name, currentStage: kind === "mash" ? "mash" : "fermentation", status: kind === "mash" ? "brewing" : "fermenting", stageStartedAt: now - day * DAY,
    recipe: { id: "eval-recipe", name: recipe.name }, recipeSnapshot: recipe, splits: kind === "splits" ? sunsetSplits().map((split, index) => ({ ...split, volumeL: 10, vessel: `Evalkar ${index + 1}` })) : [] });
  const timeline: TimelineItem[] = [];
  const measurement = (value: number, measurementKind: MeasurementKind, offsetDays = 0, stage: TimelineItem["stage"] = "fermentation") => {
    const id = `eval-${timeline.length}`;
    timeline.push({ id, type: "measurement", stage, splitId: null, occurredAt: now - offsetDays * DAY, createdAt: now - offsetDays * DAY,
      createdBy: { id: "eval-brewer", name: "Testbrygger" }, data: null, comment: null, attachment: null,
      measurement: { id, kind: measurementKind, value, unit: measurementKindSpecs[measurementKind].unit!, enteredValue: value, enteredUnit: measurementKindSpecs[measurementKind].unit!, label: null, valueMin: null, valueMax: null, sampleTempC: null, instrument: null, comment: null } });
  };
  if (day > 0) timeline.push({ id: "fermentation-start", type: "fermentation_started", stage: "fermentation", splitId: null,
    occurredAt: batch.stageStartedAt!, createdAt: batch.stageStartedAt!, createdBy: { id: "eval-brewer", name: "Testbrygger" }, data: null,
    measurement: null, comment: null, attachment: null });
  if (kind === "logged") measurement(18, "temperature");
  if (kind === "corrected") {
    measurement(20.2, "temperature");
    timeline.at(-1)!.data = { corrections: { originalId: "removed-reading", correctedBy: "eval-brewer" } };
    timeline.at(-1)!.measurement!.comment = "Korrigert fra feilregistrert 18 °C; bare 20,2 °C er gjeldende.";
  }
  if (kind === "stable") {
    measurement(1.05, "sg", 8, "cooling");
    for (const day of [3, 2, 1, 0]) measurement(1.012, "sg", day);
    timeline.push({ id: "dry-hop", type: "ingredient_added", stage: "fermentation", splitId: null, occurredAt: now - 4 * DAY, createdAt: now - 4 * DAY,
      createdBy: { id: "eval-brewer", name: "Testbrygger" }, data: { id: "dry", ingredientId: "dry", name: "Eval hop", amount: 80, unit: "g", use: "dry_hop" }, measurement: null, comment: null, attachment: null });
  }
  timeline.sort((a, b) => a.occurredAt - b.occurredAt);
  return { batch, timeline, now };
}
